# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
