# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_dependent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='image',
        ),
    ]
