# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0004_auto_20190226_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinations',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinations',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
