# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0006_auto_20190227_2357'),
        ('meds', '0006_auto_20190228_1223'),
    ]

    operations = [
    ]
